### ISSUE TITLE
The application gets stuck after configuring the connection.

### ISSUE THREAD

**Issue by matzefriedrich** [zLeki/GolangDB#2]
If an empty (or missing) configuration is detected, the application prompts the user to provide the connection parameters. Once the settings are written to the JSON file, the application does not exit nor navigate to the tables view.

![image](https://user-images.githubusercontent.com/1573457/229866421-d6016213-9b50-458b-88f5-00cac0cb394b.png)

This is because of a missing assignment to the `types.BaseStruct` variable (I would say).

**Comment by matzefriedrich** [comment]
A fix is available by pull request #4

**Comment by benjaminsabella** [comment]
Thank you, I hadn't noticed
